POST http://localhost:5000/api/auth/sign-up
Content-Type: application/json
Authorization: Bearer {{$dotenv APP_TOKEN}}

{
  "username": "admin01",
  "email": "admin01@email.com",
  "password": "admin01",
  "role": "ADMIN"
}
